apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-test
spec:
  replicas: 2
  template:
    metadata:
      annotations:
        h3poteto.dev.fluentd-sidecar-injection: "true"
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
