apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-annotate-webhook
  labels:
    app: pod-annotate-webhook
    kind: mutator
webhooks:
  - name: pod-annotate-webhook.h3poteto.dev
    clientConfig:
      service:
        name: pod-annotate-webhook
        namespace: default
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMzVENDQWNVQ0ZDM2lxcTJaYmJ1TVBLbUhXNnk5KzQ5Z1lyanBNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1Dc3gKS1RBbkJnTlZCQU1NSUhCdlpDMWhibTV2ZEdGMFpTMTNaV0pvYjI5ckxtUmxabUYxYkhRdWMzWmpNQjRYRFRJdwpNREV6TURBM05USXlOMW9YRFRJeE1ERXlPVEEzTlRJeU4xb3dLekVwTUNjR0ExVUVBd3dnY0c5a0xXRnVibTkwCllYUmxMWGRsWW1odmIyc3VaR1ZtWVhWc2RDNXpkbU13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUUN4OGNLUm1ycVNva2JoSHE0VzZTYTcrVmR6bG5lWnRkV2s3Zjh5UTFCZFA3emI1Snlza2RDeQpzd2tVaEkxOFhBNkNuRlN3Z2ttZnRGVXpDV1NSSS96bnFUaUptVncyVVpVejhYRmhkZkF2UkhOTTBRdGJYSjVKCmtGb0VjSDJIeS9JWW51eUg0ZXUxaHk1T0dOREd4bWpocGFGTE5sQXhRQWk5RjQ4YlZ6NERzVnB1UzIxWW9pTTUKM1Zva2RGVkdXQllTZXF3RW9WL0hGUEF1V1Nvbk1HVGI4S0RtSXlXWUx5WTN6V3ZWcElRa3p5empiZnEyRE9nUQpNSWtJaGQrdGNDN1BiQWhWNHdPcFJwQURKYzZ6cE5HdTZaZ2ppNTU4OWRQa3ZMNjY0RG9rODZOd0Q0QWRaRldTCkdBYlFyMFdzR0EvOVhuVmhzWS8vT2QvcEY3ZVA1c2ZoQWdNQkFBRXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUIKQUhmYzVLMjRGMGZXTkxDZXpFUUhJelkrV0NPcHFxR0RxTGkvT3dLT1VZamprQzR0bmtGa29aYkJlSCt2VWlSMgo2ZzdFc2FrcllUQ0prNG9kSk9IS2FzSFRNU3JLZXRQU0FkKzZKSlo2cUoxY2tjRlVsb1NZNzJOWm5Ka21INFViCkN0ZEdQV2FPYUsrMGhHanJqYWRZUVRERVRGejh1Q2hxUFJ1bVdFWmxlMlhYUm9vWXk5dUQwWVRINTRwMVRHVEQKQWNiWEhsMEpCUXR1VTFGaHRuZExObmUvVk5xSEpPZ1ZxdGVJekpZWXhQQlRQN2k0QURGcmo2NXlmcDhKcmFTVgpwTGcxK05jYTZMYnJpdm1kOGFPUnhiOTJ6R2FyQ24yMDlzWVU0eGdkTVp1Tng3MDN1bTFLM1JYZGdxWGtnNjdGCkRwYW9Ec1ZnOU1JLzUyY1Iya1pKUUk0PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
